<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_socket_runtime_exc1cc17ff15ee3bc97d249f00c72f41b97" kind="class" language="Python" prot="public">
    <compoundname>NEAT_PyGenetics::NEAT::ErrorHandling::Exceptions::SocketRuntimeException::SocketRuntimeException</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_socket_runtime_exc1cc17ff15ee3bc97d249f00c72f41b97_1a747071f76bd0ecd08342e4ac9d7a5e33" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.SocketRuntimeException.SocketRuntimeException.__init__</definition>
        <argsstring>(self, message=&quot;&quot;, errors=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>message</type>
          <defname>message</defname>
          <defval>&quot;&quot;</defval>
        </param>
        <param>
          <type>errors</type>
          <defname>errors</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="NEAT/ErrorHandling/Exceptions/SocketRuntimeException.py" line="2" column="1" bodyfile="NEAT/ErrorHandling/Exceptions/SocketRuntimeException.py" bodystart="2" bodyend="6"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="186">
        <label>Exception</label>
      </node>
      <node id="185">
        <label>NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.SocketRuntimeException.SocketRuntimeException</label>
        <link refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_socket_runtime_exc1cc17ff15ee3bc97d249f00c72f41b97"/>
        <childnode refid="186" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="188">
        <label>Exception</label>
      </node>
      <node id="187">
        <label>NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.SocketRuntimeException.SocketRuntimeException</label>
        <link refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_socket_runtime_exc1cc17ff15ee3bc97d249f00c72f41b97"/>
        <childnode refid="188" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="NEAT/ErrorHandling/Exceptions/SocketRuntimeException.py" line="1" column="1" bodyfile="NEAT/ErrorHandling/Exceptions/SocketRuntimeException.py" bodystart="1" bodyend="6"/>
    <listofallmembers>
      <member refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_socket_runtime_exc1cc17ff15ee3bc97d249f00c72f41b97_1a747071f76bd0ecd08342e4ac9d7a5e33" prot="public" virt="non-virtual"><scope>NEAT_PyGenetics::NEAT::ErrorHandling::Exceptions::SocketRuntimeException::SocketRuntimeException</scope><name>__init__</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
