<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_socket_already_usec2845100a8624939d4f1ab320dc8a73f" kind="class" language="Python" prot="public">
    <compoundname>NEAT_PyGenetics::NEAT::ErrorHandling::Exceptions::SocketAlreadyUsedException::SocketAlreadyUsedException</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_socket_already_usec2845100a8624939d4f1ab320dc8a73f_1aa78052a441ad0d25947f06f3ed625c1c" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.SocketAlreadyUsedException.SocketAlreadyUsedException.__init__</definition>
        <argsstring>(self, message=&quot;&quot;, errors=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>message</type>
          <defname>message</defname>
          <defval>&quot;&quot;</defval>
        </param>
        <param>
          <type>errors</type>
          <defname>errors</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="NEAT/ErrorHandling/Exceptions/SocketAlreadyUsedException.py" line="2" column="1" bodyfile="NEAT/ErrorHandling/Exceptions/SocketAlreadyUsedException.py" bodystart="2" bodyend="6"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="182">
        <label>Exception</label>
      </node>
      <node id="181">
        <label>NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.SocketAlreadyUsedException.SocketAlreadyUsedException</label>
        <link refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_socket_already_usec2845100a8624939d4f1ab320dc8a73f"/>
        <childnode refid="182" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="184">
        <label>Exception</label>
      </node>
      <node id="183">
        <label>NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.SocketAlreadyUsedException.SocketAlreadyUsedException</label>
        <link refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_socket_already_usec2845100a8624939d4f1ab320dc8a73f"/>
        <childnode refid="184" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="NEAT/ErrorHandling/Exceptions/SocketAlreadyUsedException.py" line="1" column="1" bodyfile="NEAT/ErrorHandling/Exceptions/SocketAlreadyUsedException.py" bodystart="1" bodyend="6"/>
    <listofallmembers>
      <member refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_socket_already_usec2845100a8624939d4f1ab320dc8a73f_1aa78052a441ad0d25947f06f3ed625c1c" prot="public" virt="non-virtual"><scope>NEAT_PyGenetics::NEAT::ErrorHandling::Exceptions::SocketAlreadyUsedException::SocketAlreadyUsedException</scope><name>__init__</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
