<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="namespace_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_socket_runtime_exception" kind="namespace" language="Python">
    <compoundname>NEAT_PyGenetics::NEAT::ErrorHandling::Exceptions::SocketRuntimeException</compoundname>
    <innerclass refid="class_n_e_a_t___py_genetics_1_1_n_e_a_t_1_1_error_handling_1_1_exceptions_1_1_socket_runtime_exc1cc17ff15ee3bc97d249f00c72f41b97" prot="public">NEAT_PyGenetics::NEAT::ErrorHandling::Exceptions::SocketRuntimeException::SocketRuntimeException</innerclass>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <location file="NEAT/ErrorHandling/Exceptions/SocketRuntimeException.py" line="1" column="1"/>
  </compounddef>
</doxygen>
